apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 1 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: your-custom-image:latest 
            env:
            - name: POSTGRES_USER
              value: "your-postgres-user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              value: "your-database-name"
            - name: POSTGRES_HOST
              value: "your-postgres-host"
            - name: AWS_S3_BUCKET
              value: "your-s3-bucket-name"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_secret_access_key
          restartPolicy: OnFailure
